# Generated by Django 4.2.1 on 2023-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datestart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
